set -g history-limit 65000
set-window-option -g mode-keys vi

# Renumber windows when one is closed
set -g renumber-windows on

# Display tmux messages for 4 seconds
set -g display-time 4000

# Enable mouse support
set -g mouse on

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on

# Reduce escape time (helpful for vim)
set -sg escape-time 10
